/**
 * Terrain conformance. The Ruby `Starc::Sim::Terrain` and this module are two
 * implementations of `shared/TERRAIN.md` and must agree, because unit Z in a
 * snapshot comes from the server and the ground is drawn from here. A
 * divergence makes units visibly float.
 *
 * The constants below were generated by the Ruby implementation and are the
 * cross-language contract. `server/spec/terrain_conformance_spec.rb` asserts
 * the same table from the other side.
 */
import { describe, expect, it } from "vitest";
import { HeightField, heightField, AIR_ALTITUDE } from "./heightfield";
import { GAME } from "@shared/gameData";
import type { MapDef } from "@shared/protocol";

const map = (id: string): MapDef => {
  const found = GAME.maps.find((m) => m.id === id);
  if (!found) throw new Error(`unknown map ${id}`);
  return found;
};

/** Ruby: Starc::Sim::Terrain.for("altaior").height_at(x, z) */
const ALTAIOR_CONFORMANCE: readonly (readonly [number, number, number])[] = [
  [0, 0, 0],
  [1, 1, 0],
  [128, 128, 1.891704263],
  [256, 256, 0],
  [255, 255, 0],
  [64, 192, 1.870294974],
  [200, 37, 1.581327888],
  [13, 250, 0.580808929],
  [77, 91, 1.476525517],
  [190, 166, 1.558226067],
];

describe("HeightField", () => {
  it("matches the Ruby implementation at the conformance points", () => {
    const field = new HeightField(map("altaior"));
    for (const [x, z, expected] of ALTAIOR_CONFORMANCE) {
      expect(field.sample(x, z), `height_at(${x}, ${z})`).toBeCloseTo(expected, 9);
    }
  });

  it("agrees with the server bit-exactly at the conformance points", () => {
    // A float64 multiply overflow in the lattice hash shifts results by ~1e-6
    // — invisible to `toBeCloseTo(5)` but enough to make units float, so the
    // contract is exactness, not approximation.
    const field = new HeightField(map("altaior"));
    const exact = new Map(ALTAIOR_CONFORMANCE.map(([x, z, h]) => [`${x},${z}`, h]));
    for (const [key, expected] of exact) {
      const [x, z] = key.split(",").map(Number);
      expect(Math.abs(field.sample(x, z) - expected)).toBeLessThan(1e-9);
    }
  });

  it("flattens the 16 m border so the map edge never clips open", () => {
    const field = new HeightField(map("altaior"));
    const corner = field.sample(0, 0);
    for (let t = 0; t <= 16; t += 2) {
      expect(Math.abs(field.sample(t, 0) - corner)).toBeLessThan(1e-6);
      expect(Math.abs(field.sample(0, t) - corner)).toBeLessThan(1e-6);
    }
  });

  it("interpolates bilinearly rather than snapping to the integer grid", () => {
    const field = new HeightField(map("altaior"));
    // Find a lattice point on a genuine slope.
    let x = 0;
    let z = 0;
    for (let i = 0; i < 256 && field.slope(i, i) < 0.01; i++) {
      x = i;
      z = i;
    }
    const a = field.sample(x, z);
    const b = field.sample(x + 1, z);
    const mid = field.sample(x + 0.5, z);
    expect(Math.abs(a - b)).toBeGreaterThan(0.01);
    expect(mid).toBeCloseTo((a + b) / 2, 12);
  });

  it("clamps out-of-bounds queries to the map edge instead of returning garbage", () => {
    const field = new HeightField(map("altaior"));
    expect(field.sample(-50, -50)).toBe(field.sample(0, 0));
    expect(field.sample(9999, 9999)).toBe(field.sample(256, 256));
  });

  it("reports unit surface normals and a zero slope on flat ground", () => {
    const field = new HeightField(map("altaior"));
    const n = field.normal(0, 0);
    expect(Math.hypot(n.x, n.y, n.z)).toBeCloseTo(1, 12);
    expect(n.y).toBeCloseTo(1, 12);
    expect(field.slope(0, 0)).toBeCloseTo(0, 12);
  });

  it("agrees passable with height above the water line", () => {
    const field = new HeightField(map("altaior"));
    for (let i = 0; i < 64; i++) {
      const x = (i * 4) % 256;
      const z = (i * 7) % 256;
      expect(field.passable(x, z)).toBe(field.sample(x, z) > 0);
    }
  });

  it("derives a different surface per map from its terrain seed", () => {
    const grassland = new HeightField(map("altaior"));
    const badlands = new HeightField(map("cataclysm"));
    expect(grassland.sample(128, 128)).not.toBeCloseTo(badlands.sample(128, 128), 6);
  });

  it("caches one instance per map id", () => {
    expect(heightField(map("altaior"))).toBe(heightField(map("altaior")));
    expect(heightField(map("altaior"))).not.toBe(heightField(map("chokepoint")));
  });

  it("exposes the air altitude the simulation also uses", () => {
    expect(AIR_ALTITUDE).toBe(6);
  });
});
